### ISSUE TITLE
call of custom nlp from google assistant

### ISSUE THREAD

**Issue by amithit** [RasaHQ/tutorial-rasa-google-assistant#14]
Hi  All,
I am trying to setup google assitant project and want to call custom nlp , but during the creation of google assistant project their is no option for 
https://rasa.com/blog/going-beyond-hey-google-building-a-rasa-powered-google-assistant/
Please help how to call my custom nlp service from google assistant.
Thank you

**Comment by sara-tagger** [comment]
Thanks for the issue, @losterloh will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by losterloh** [comment]
hey @amithit! For help on how to set up your assistant, please ask your question on the [Rasa community forum](https://forum.rasa.com/).
