### ISSUE TITLE
Docker-compose example

### ISSUE THREAD

**Issue by martyer** [RasaHQ/tutorial-rasa-google-assistant#3]
Hey there,

I implemented this in Docker. As this is quite outdated. Would you be interested in the docker implementation? I would be willing to share it.

**Comment by Faadal** [comment]
I would love to have it man

**Comment by GV2019** [comment]
Hi Martyer, 

Currently I'm also trying to implement this in Docker. It would be really helpful if you could share. Thanks!

**Comment by martyer** [comment]
I published my setup here: https://github.com/genistat-ag/tutorial-rasa-google-assistant
